version: "3.8"

services:
  database:
    image: mysql:8.0
    container_name: mysql-server
    restart: unless-stopped
    env_file: ./docker.env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mysqlnet
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  db-data:

networks:
  mysqlnet:
    driver: bridge